@startuml casos
left to right direction

actor Cliente as c
actor Gerente as g

rectangle Sistema {
    usecase "Cadastro de Cliente" as cad_cli
    usecase "Login de Cliente" as login_cli
    usecase "Atualização de Conta de Cliente" as atual_cli
    usecase "Remoção de Conta de Cliente" as rem_cli
    usecase "Listagem de Clientes" as list_cli
    usecase "Busca de Cliente" as busca_cli
    usecase "Cadastro de Gerente" as cad_ger
    usecase "Login de Gerente" as login_ger
    usecase "Atualização de Conta de Gerente" as atual_ger
    usecase "Remoção de Conta de Gerente" as rem_ger
    usecase "Listagem de Gerentes" as list_ger
    usecase "Cadastro de Produto" as cad_prod
    usecase "Atualização de Produto" as atual_prod
    usecase "Remoção de Produto" as rem_prod
    usecase "Listagem de Produtos" as list_prod
    usecase "Cadastro de Ingrediente" as cad_ing
    usecase "Listagem de Ingredientes" as list_ing
    usecase "Fazer Pedido" as fazer_ped
    usecase "Atualizar Pedido" as atual_ped
    usecase "Cancelar Pedido" as cancelar_ped
    usecase "Listar Pedidos" as listar_ped
    usecase "Listar Pedidos por Cliente" as listar_ped_cli
    usecase "Buscar Pedido" as buscar_ped
}

c --> cad_cli
c --> login_cli
c --> atual_cli
c --> rem_cli
c --> fazer_ped
c --> cancelar_ped

sistema --> list_prod
sistema --> listar_ped_cli

g --> cad_ger
g --> login_ger
g --> atual_ger
g --> rem_ger
g --> list_ger
g --> list_cli
g --> busca_cli
g --> cad_prod
g --> atual_prod
g --> rem_prod
g --> cad_ing
g --> list_ing
g --> listar_ped
g --> atual_ped
g --> buscar_ped

@enduml